<?php

namespace App\Services;

use App\Models\WordPressSite;
use Exception;

class MonitoringScriptDeployer
{
    /**
     * Deploy monitoring script to remote server
     */
    public function deploy(WordPressSite $site, string $apiToken): array
    {
        try {
            // Connect to server
            $ssh = new SSHService($site->server_ip, $site->server_port);
            
            if ($site->server_ssh_key) {
                $ssh->connectWithKey($site->server_username, $site->server_ssh_key);
            } else {
                $ssh->connectWithPassword($site->server_username, $site->server_password);
            }

            // Generate monitoring script content
            $scriptContent = $this->generateScript($apiToken);

            // Upload script
            $ssh->createFile('/usr/local/bin/docker-monitor.sh', $scriptContent);
            
            // Make it executable
            $ssh->execute('chmod +x /usr/local/bin/docker-monitor.sh');
            
            // Create log file
            $ssh->execute('touch /var/log/docker-monitor.log');
            $ssh->execute('chmod 666 /var/log/docker-monitor.log');
            
            // Check if cron job exists
            $cronCheck = $ssh->execute('crontab -l 2>/dev/null | grep docker-monitor.sh');
            
            if (!$cronCheck['success'] || empty(trim($cronCheck['output']))) {
                // Add cron job
                $ssh->execute('(crontab -l 2>/dev/null; echo "*/5 * * * * /usr/local/bin/docker-monitor.sh") | crontab -');
            }

            $ssh->disconnect();

            return [
                'success' => true,
                'message' => 'Monitoring script deployed successfully',
            ];

        } catch (Exception $e) {
            return [
                'success' => false,
                'message' => 'Failed to deploy monitoring script: ' . $e->getMessage(),
            ];
        }
    }

    /**
     * Generate monitoring script content with API configuration
     */
    protected function generateScript(string $apiToken): string
    {
        $apiEndpoint = config('app.url') . '/api/sites/status';
        
        return <<<BASH
#!/bin/bash

# Docker Container Monitor Script
# Auto-generated by WordPress Manager

# Configuration
API_ENDPOINT="{$apiEndpoint}"
API_TOKEN="{$apiToken}"
LOG_FILE="/var/log/docker-monitor.log"
TIMESTAMP=\$(date '+%Y-%m-%d %H:%M:%S')

# Logging function
log_message() {
    echo "[\${TIMESTAMP}] \$1" >> "\${LOG_FILE}"
}

# Start monitoring
log_message "Starting container status check..."

# Get all WordPress containers
CONTAINERS=\$(docker ps -a --filter "name=wp_" --format "{{.Names}}|{{.Status}}|{{.ID}}")

if [ -z "\$CONTAINERS" ]; then
    log_message "No WordPress containers found"
    exit 0
fi

# Process each container
while IFS='|' read -r CONTAINER_NAME CONTAINER_STATUS CONTAINER_ID; do
    log_message "Checking container: \${CONTAINER_NAME}"
    
    # Determine status
    if [[ \$CONTAINER_STATUS == Up* ]]; then
        STATUS="running"
        MESSAGE="Container is running"
    elif [[ \$CONTAINER_STATUS == Exited* ]]; then
        STATUS="stopped"
        MESSAGE="Container is stopped: \${CONTAINER_STATUS}"
    else
        STATUS="failed"
        MESSAGE="Unknown status: \${CONTAINER_STATUS}"
    fi
    
    # Get container uptime
    UPTIME=""
    if [ "\$STATUS" == "running" ]; then
        UPTIME=\$(docker inspect --format='{{.State.StartedAt}}' "\${CONTAINER_ID}" 2>/dev/null)
    fi
    
    # Prepare JSON payload
    JSON_PAYLOAD=\$(cat <<EOF
{
    "container_name": "\${CONTAINER_NAME}",
    "status": "\${STATUS}",
    "message": "\${MESSAGE}",
    "uptime": "\${UPTIME}",
    "timestamp": "\${TIMESTAMP}"
}
EOF
)
    
    # Send status to API
    RESPONSE=\$(curl -s -X POST \\
        -H "Content-Type: application/json" \\
        -H "Authorization: Bearer \${API_TOKEN}" \\
        -d "\${JSON_PAYLOAD}" \\
        "\${API_ENDPOINT}" 2>&1)
    
    CURL_EXIT_CODE=\$?
    
    if [ \$CURL_EXIT_CODE -eq 0 ]; then
        log_message "Successfully reported status for \${CONTAINER_NAME}: \${STATUS}"
    else
        log_message "Failed to report status for \${CONTAINER_NAME}. Error: \${RESPONSE}"
    fi
    
done <<< "\$CONTAINERS"

log_message "Container status check completed"

# Clean up old log entries (keep last 1000 lines)
if [ -f "\${LOG_FILE}" ]; then
    TEMP_FILE="\${LOG_FILE}.tmp"
    tail -n 1000 "\${LOG_FILE}" > "\${TEMP_FILE}"
    mv "\${TEMP_FILE}" "\${LOG_FILE}"
fi
BASH;
    }

    /**
     * Remove monitoring script from remote server
     */
    public function remove(WordPressSite $site): array
    {
        try {
            $ssh = new SSHService($site->server_ip, $site->server_port);
            
            if ($site->server_ssh_key) {
                $ssh->connectWithKey($site->server_username, $site->server_ssh_key);
            } else {
                $ssh->connectWithPassword($site->server_username, $site->server_password);
            }

            // Remove cron job
            $ssh->execute('crontab -l 2>/dev/null | grep -v docker-monitor.sh | crontab -');
            
            // Remove script
            $ssh->execute('rm -f /usr/local/bin/docker-monitor.sh');

            $ssh->disconnect();

            return [
                'success' => true,
                'message' => 'Monitoring script removed successfully',
            ];

        } catch (Exception $e) {
            return [
                'success' => false,
                'message' => 'Failed to remove monitoring script: ' . $e->getMessage(),
            ];
        }
    }
}