/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "register.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "home": [],
    "dashboard": [],
    "servers.index": [],
    "servers.create": [],
    "servers.store": [],
    "servers.show": [
        {
            "name": "server",
            "required": true,
            "binding": "id"
        }
    ],
    "servers.edit": [
        {
            "name": "server",
            "required": true,
            "binding": "id"
        }
    ],
    "servers.update": [
        {
            "name": "server",
            "required": true,
            "binding": "id"
        }
    ],
    "servers.destroy": [
        {
            "name": "server",
            "required": true,
            "binding": "id"
        }
    ],
    "sites.index": [],
    "sites.create": [],
    "sites.store": [],
    "sites.show": [
        {
            "name": "site",
            "required": true,
            "binding": "id"
        }
    ],
    "sites.edit": [
        {
            "name": "site",
            "required": true,
            "binding": "id"
        }
    ],
    "sites.update": [
        {
            "name": "site",
            "required": true,
            "binding": "id"
        }
    ],
    "sites.destroy": [
        {
            "name": "site",
            "required": true,
            "binding": "id"
        }
    ],
    "sites.start": [
        {
            "name": "site",
            "required": true,
            "binding": "id"
        }
    ],
    "sites.stop": [
        {
            "name": "site",
            "required": true,
            "binding": "id"
        }
    ],
    "sites.restart": [
        {
            "name": "site",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "user-password.edit": [],
    "user-password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
