version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wp_6925ab0645548_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: BOWmlWRdEVa4hsHL
      MYSQL_DATABASE: wordpress_new
      MYSQL_USER: wpuser_new
      MYSQL_PASSWORD: 4L7EKxqhkG04mCSz
    networks:
      - wp_6925ab0645548_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  wordpress:
    depends_on:
      db:
        condition: service_healthy
    image: wordpress:latest
    container_name: wp_6925ab0645548
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser_new
      WORDPRESS_DB_PASSWORD: 4L7EKxqhkG04mCSz
      WORDPRESS_DB_NAME: wordpress_new
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_6925ab0645548_network

  wpcli:
    depends_on:
      wordpress:
        condition: service_started
    image: wordpress:cli
    container_name: wp_6925ab0645548_cli
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_6925ab0645548_network
    entrypoint: /bin/sh
    command: >
      -c "
      sleep 30;
      wp core install
        --url=http://localhost:8080
        --title='wordpress_new'
        --admin_user='admin'
        --admin_password='admin***'
        --admin_email='admin@gmail.com'
        --skip-email
        --allow-root || echo 'WordPress already installed';
      exit 0
      "

volumes:
  db_data:
  wordpress_data:

networks:
  wp_6925ab0645548_network:
    driver: bridge